Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> Hi Luca,
>   I wasn't able to run the Message apps unit tests (they are failing). I am working on fixing them. They used to run, but they got broken. Thanks
> 
>   $ adb shell am instrument -w com.android.messaging.test
>   $ atest

I get these errors but they are not related to my change
android.test.suitebuilder.TestSuiteBuilder$FailedToCreateTests:
Error in testSuiteConstructionFailed:
java.lang.RuntimeException: Exception during suite construction
	at android.test.suitebuilder.TestSuiteBuilder$FailedToCreateTests.testSuiteConstructionFailed(TestSuiteBuilder.java:244)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:564)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2196)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.test.suitebuilder.TestMethod.instantiateTest(TestMethod.java:91)
	at android.test.suitebuilder.TestMethod.createTest(TestMethod.java:77)
	at android.test.suitebuilder.TestSuiteBuilder.addTest(TestSuiteBuilder.java:259)
	at android.test.suitebuilder.TestSuiteBuilder.build(TestSuiteBuilder.java:185)
	at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:390)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6492)
	at android.app.ActivityThread.access$1300(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7396)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/messaging/ui/conversation/ConversationFragment;
	at com.android.messaging.ui.conversation.ConversationFragmentTest.<init>(ConversationFragmentTest.java:67)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.android.messaging.ui.conversation.ConversationFragment
	... 17 more

Test results for InstrumentationTestRunner=.E
Time: 0.001

FAILURES!!!
Tests run: 1,  Failures: 0,  Errors: 1

Patch-set: 8
Reviewer: Gerrit User 1081223 <1081223@85c56323-6fa9-3386-8a01-6480fb634889>